# Generated by Django 3.2.9 on 2021-11-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocioTorcedor', '0002_alter_plano_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='nome',
            new_name='name',
        ),
    ]
