# Generated by Django 3.2.9 on 2021-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocioTorcedor', '0003_rename_nome_plano_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
