# Generated by Django 3.2.9 on 2021-11-23 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocioTorcedor', '0004_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAdquirido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SocioTorcedor.plano')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SocioTorcedor.usuario')),
            ],
        ),
    ]
